language: python

sudo: false

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

cache:
    directories:
        - $HOME/.data

dist: xenial

install:
    - pip install -U pip
    - pip install jaxlib
    - pip install jax
    - pip install .[examples,test]
    - pip freeze

branches:
    only:
        - master

jobs:
    include:
        - stage: lint
          python: 3.6
          script: make lint
        - stage: unit
          name: "unit tests"
          python: 3.6
          script: make test -m "not test_examples"
        - name: "examples"
          python: 3.6
          script: make test -m test_examples
